var date = new Date()
console.log(date)
var year = date.getFullYear()
console.log(year)
var month = date.getMonth()
console.log(month)
var month = date.getMonth() + 1
console.log(month)
var day = date.getDate()
console.log(day)
var day = date.getDay()
console.log(day)
var hour = date.getHours()
console.log(hour)
var minute = date.getMinutes()
console.log(minute)
var seconds = date.getSeconds()
console.log(seconds)